severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  ColorVariable:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: false

  ImportantRule:
    enabled: false

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: false

  TrailingWhitespace:
    enabled: false

  UrlFormat:
      enabled: false

  UrlQuotes:
      enabled: false
  Comment:
      enabled: false